import { Metadata } from "next";
import "./index.css";

// 加载标题显示
export const metadata: Metadata = {
  title: "面试宝刷题平台",
  description: "Generated by create next app",
};

export default function HomePage() {
  return <div id={"homePage"}>主页</div>;
}
